### ISSUE TITLE
Pressure should be in Pascals instead of millibars

### ISSUE THREAD

**Issue by duanemaxwell** [joeyjyyang/sensehat_driver#10]
According to ROS docs, std_msgs:FluidPressure should be reported in Pascals instead of millibars, simple fix is to multiply the value by 100.0

sensehat_driver/sensehat_environment_publisher.py Line 42:

`        self.air_pressure_msg.fluid_pressure = self.air_pressure*100.0`

Probably should also consider changing line 32 to match as well, depending upon how it's to be used - is it intended to be raw data, or compatible with the std_msgs?

**Comment by joeyjyyang** [comment]
Fixed in https://github.com/joeyjyyang/ros_sensehat/commit/686d00097b1ac734588f17fcfe863c8800c53bfa
