### ISSUE TITLE
Malformed XML in launch/sensehat_environment.launch

### ISSUE THREAD

**Issue by duanemaxwell** [joeyjyyang/sensehat_driver#9]
Missing closing double quote on line 5:

`<param name="spin_rate" type="double" value="30.0 />`

should be:

`<param name="spin_rate" type="double" value="30.0" />`

**Comment by joeyjyyang** [comment]
Fixed in https://github.com/joeyjyyang/ros_sensehat/commit/dd3dc78d615b8cac4e1c592d28e41a81d3c2c529#
